/*
 * Copyright 2013 David Kunzler
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */

package de.devland.esperandro;

import org.junit.Assert;
import org.junit.Test;

import de.devland.esperandro.tests.EsperandroSimpleExampleKeys;

public class KeyGenerationTest {

    @Test
    public void testKeyClassExists() {
        // this automatically checks that the class was generated by loading it
        Assert.assertEquals("Wrong name of generated key file.", "EsperandroSimpleExampleKeys",
                EsperandroSimpleExampleKeys.class.getSimpleName());
    }

    @Test
    public void testKeyClassEntries() {
        Assert.assertEquals(EsperandroSimpleExampleKeys.boolPref, "boolPref");
        Assert.assertEquals(EsperandroSimpleExampleKeys.floatPref, "floatPref");
        Assert.assertEquals(EsperandroSimpleExampleKeys.integerPref, "integerPref");
        Assert.assertEquals(EsperandroSimpleExampleKeys.longPref, "longPref");
        Assert.assertEquals(EsperandroSimpleExampleKeys.stringPref, "stringPref");
        Assert.assertEquals(EsperandroSimpleExampleKeys.stringPrefWithBooleanPutter, "stringPrefWithBooleanPutter");
        Assert.assertEquals(EsperandroSimpleExampleKeys.stringSetPref, "stringSetPref");
    }
}
